### ISSUE TITLE
bug: lint failed

### ISSUE THREAD

**Issue by huantt** [tonkeeper/tonapi-go#19]
![image](https://github.com/tonkeeper/tonapi-go/assets/19801770/6ad02d91-9963-4367-899b-a78d19411182)

The code on the main branch is not valid. Please run golint before pushing to the main branch.

**Comment by huantt** [comment]
Detail: this function requires returning uint32 but `res.Seqno` is init32

**Comment by aleksej-paschenko** [comment]
the issue looks solved, closing it
