### ISSUE TITLE
Transaction details of an account showing wrong values for success and aborted

### ISSUE THREAD

**Issue by gholami-mohammad** [tonkeeper/tonapi-go#38]
Problem:
I'm using tonapi-go to get list of transactions of an account.  The wallet has some TON, DOGES, and NOTCOIN values.
on deposit transactions, there is transactions with InMsg->DecodedOpName with value of `jetton_notify`

When checking details of this transaction, values of success and aborted fields are not correct.

The tx hash mentioned in this sample is tx hash of NOT coin deposit on my wallet.
```
func getTxDetails() {
	txHash := "054fec2e61a1d78fb3f2a934b7f7f15c77301af82090df413c4404cca77e9eb5"

	client, err := tonapi.New()
	if err != nil {
		log.Fatalln(err)
	}

	tx, err := client.GetBlockchainTransaction(context.Background(), tonapi.GetBlockchainTransactionParams{
		TransactionID: txHash,
	})
	if err != nil {
		log.Fatalln(err)
	}

	fmt.Println("success:", tx.Success)
	fmt.Println("aborted:", tx.Aborted)
}
```

`tx.Success` expected to be TRUE but it is FALSE and also tx.Aborted should be FALSE but it is TRUE.

**Comment by Shemse1** [comment]
func getTxDetails() {

	txHash := "054fec2e61a1d78fb3f2a934b7f7f15c77301af82090df413c4404cca77e9eb5"



	client, err := tonapi.New()

	if err != nil {

		log.Fatalln(err)

	}



	tx, err := client.GetBlockchainTransaction(context.Background(), tonapi.GetBlockchainTransactionParams{

		TransactionID: txHash,

	})

	if err != nil {

		log.Fatalln(err)

	}



	fmt.Println("success:", tx.Success)

	fmt.Println("aborted:", tx.Aborted)

}

**Comment by aleksej-paschenko** [comment]
@gholami-mohammad  
TONAPI shows correct data. The transaction was aborted. The tx's value is 0.000000001 TON. That is not enough to run TVM. The compute phase was skipped with **cskip_no_gas** reason. 

But that is OK with jetton notify
