### ISSUE TITLE
gasless example (Error:failed to resolve jetton master: account not found)

### ISSUE THREAD

**Issue by surname0990** [tonkeeper/tonapi-go#40]
I have not changed the contract address; I have checked it, and it is correct. I can’t understand why it can’t find it, and I haven’t changed the client either.

contract addres - EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs

go run main.go
Wallet address: 0:d549dd46d01849335378571f3663e2e70f650d1fc8e6054c1c0265f3866041c7
Available gas jettons:
Gas jetton master: 0:f4bdd480fcd79d47dbaf6e037d1229115feb2e7ac0f119e160ebd5d031abdf2e
Gas jetton master: 0:2f956143c461769579baef2e32cc2d7bc18283f40d20bb03e432cd603ac33ffc
Gas jetton master: 0:b113a994b5024a16719f69139328eb759596c38a25f59028b146fecdc3621dfe
Gas jetton master: 0:afc49cb8786f21c87045b19ede78fc6b46c51048513f8e9a6d44060199c1bf0c
Relay address to send fees to: 0:dfbd5be8497fdc0c9fcbdfc676864840ddf8ad6423d6d5657d9b0e8270d6c8ac
[223 189 91 232 73 127 220 12 159 203 223 198 118 134 72 64 221 248 173 100 35 214 213 101 125 155 14 130 112 214 200 172]
decode response: error: code 400: {Error:failed to resolve jetton master: account not found}

**Comment by alisam1189** [comment]
OK. Tanks

در تاریخ یکشنبه ۱۵ سپتامبر ۲۰۲۴،‏ ۰۶:۴۰ George ***@***.***>
نوشت:
